### PR TITLE
Allow for creation on instance put requests.

### PR DESCRIPTION
**Pull request by porsager**
I think it makes sense to be able to create documents using instance put. This also allows for making an upsert like request to the api.

### CODE REVIEW

**Comment by pjmolina** [comment]
Hi. Looking at the principles followed by @wprl on the design of baucis as RESTfull and mapping to CRUD in this way:

- [Use PUT for Partial Updates in your REST API](http://kun.io/blog/articles/use-put-for-partial-updates/index.html)
- [PATCH, Idempotence, & the Importance of Standards](http://kun.io/blog/articles/patch-idempotence-and-the-importance-of-standards/index.html)

I understand coherent to:

- Keep `PUT` only for *updates*
- And create new resources via a `POST`

Doing an *upsert* could do the trick for your particular case, but brokes the expected semantics on baucis IMHO for the general case.

Regards,

**Comment by porsager** [comment]
I see your point, but now that he already refers to RFC2616 it might make sense to look at their definition of put which starts with:

> If the Request-URI does not point to an existing resource, and that URI is capable of being defined as a new resource by the requesting user agent, the origin server can create the resource with that URI. http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6

Maybe it should be a setting on the controller to allow it?

**Comment by wprl** [comment]
It's definitely valid by the RFCs. In this scenario, POST creates a new resource under the resource pointed to by the URL, like a file directory structure. On the other hand, PUT can be used to create a resource at (not under) a specified URL. That being said, does it add useful functionality to have this feature?  Does it diminish functionality not having this feature?

**Comment by pjmolina** [comment]
You are right @porsager & @wprl creation on PUT is also possible as stated by the RFC.

However, in Baucis I see the assumption of using only PUT for edit, and POST for creation as very useful (IMO) for: *Middleware simplicity and maintainability.*

I will try to explain with an example: I have created some middleware to extend baucis on creation, on edit for different concerns: authorization, data validation or calling third-party systems.

To hook on pre/post middleware to PUT and POST operations to add more functionality is doable in a clean way considering the expectation of only creation on POSTs and only edit on PUTs.

Now consider the contrary: if a PUT operation could be a insert or update (*upsert*) there is no clear way to know *a-priori* (before hitting the database) if the operation is a creation or an insertion. In this scenario PRE middle-ware needs to be rewritten to deal with this mixed cases in the best case, and increase the complexity in others: 

- like authorizing for a given user permission to edit existing resources 
- but not the permission to create new resources.

Full sample with further details: The [RBAC implementation](https://studio.hivepod.io/help#authZ) on Hivepod relies on this assumption to be able to authorize (create/update) operations.

**Comment by porsager** [comment]
It prevents having to make 2 requests for services where the client is allowed to generate IDs. 

It makes the logic in the client much simpler instead of having to either GET first to check for existence, or error handle a 409 POST. 

I have both had services where the clients could generate IDs themselves, and others where the resource was synced from another source. 

I do think it might make the most sense to have as a setting just like findBy, as to not break compatibility. 

By the way. I really find Baucis awesome, so thanks a lot it!!

**Comment by pjmolina** [comment]
I found also valid your use case @porsager  
As you suggest dealing with it as an **opt-in** could work and will not break compatibility if not explicitly enabled.

**Pull request closed without merging**
